version: "3"
services: 
  aiqc:
    image: "hashrocketsyntax/aiqc:dev_desktop_v3.0.2_py3.7.12-bullseye"
    deploy:
      resources:
        limits:
          # Maximum is docker app was 8. Needs string, not int. Accepts "0.5".
          cpus: "7"
          # Maximum in docker app was 16.
          memory: 15G
    ports:
      - "8888:8888"
    volumes:
      # Source Code (allows for `import aiqc` without package installed so code can be edited/ developed).
      - "~/desktop/AIQC:/home/aiqc_usr/AIQC"
      # Working Directory (contains dev_notebooks that aren't in git repo).
      - "~/desktop/AIQC_Docker_Workspace:/home/aiqc_usr"
      # AppDirs (for aiqc database and config files). Easier than dynamically installing & running `appdirs.user_data_dir()` for different users/OS.
      - "~/desktop/AIQC_Docker_Workspace/AppDirs:/home/aiqc_usr/.local/share"
    # As opposed to `entrypoint` which is supposed to be a bash script.
    # Jupyter's file browser doesn't let you drill up out of the folder you launch it from.
    working_dir: /home/aiqc_usr
    # Serves notebooks from local directory: `/home/aiqc_usr`.
    # Access via: <http://127.0.0.1:8888/lab>.
    user: "aiqc_usr" #otherwise jupyter will complain about `--allow-root` even if you `su - aiqc_usr` to switch user first.
    command: bash -c "jupyter lab --no-browser --port 8888 --ip 0.0.0.0 --ServerApp.token='' --ServerApp.password=''"
