version: "3"
services: 
  aiqc:
    image: "aiqc:dev_v3.0.1_py3.7.12"
    deploy:
      resources:
        limits:
          # Maximum is docker app was 8. Needs string, not int. Accepts "0.5".
          cpus: "7"
          # Maximum in docker app was 16.
          memory: 15G
    ports:
      - "8888:8888"
    volumes:
      # Source Code (allows for `import aiqc` without package installed so code can be edited/ developed).
      - "~/desktop/AIQC:/home/aiqc_usr/AIQC"
      # AppDirs (for aiqc database and config files).
      - "~/desktop/AIQC_Docker_AppDirs:/home/aiqc_usr/.local/share"
      # Working Directory (contains dev_notebooks).
      - "~/desktop/AIQC_Docker_Workspace:/home/aiqc_usr"
    # As opposed to `entrypoint` which is supposed to be a bash script.
    working_dir: /home/aiqc_usr/AIQC
    # Serves notebooks from local directory: `/home/aiqc_usr`.
    # Access via: <http://127.0.0.1:8888/lab>.
    user: "aiqc_usr" #otherwise jupyter will complain about `--allow-root` even if you `su - aiqc_usr` to switch user first.
    command: bash -c "jupyter lab --no-browser --port 8888 --ip 0.0.0.0 --ServerApp.token='' --ServerApp.password=''"
